### ISSUE TITLE
PCRE .NET contact

### ISSUE THREAD

**Issue by ViktorHofer** [ltrzesniewski/pcre-net#10]
Hello Lucas,

I'm from the .NET team, currently working on System.Text.RegularExpressions. I'd love to get in contact with you to discuss your motivation of this product and a collaboration for .NET Core.

I couldn't find your email address, therefore please contact me at the address which you can find on my profile.

**Comment by ltrzesniewski** [comment]
Hi Viktor,

Sure, please check your inbox.
