### ISSUE TITLE
Rewrite to not use C++/CLI

### ISSUE THREAD

**Issue by danmosemsft** [ltrzesniewski/pcre-net#12]
Hello @ltrzesniewski I am interested in creating a .NET wrapper for PCRE2 that does not depend on C++/CLI. I was beginning work on this but I noticed you recently added a note in your README suggesting you are interested in the same goal.

My goals specifically are
1. Wrap PCRE2 so it works on all platforms where .NET Core runs. This prevents use of C++/CLI [1]
1. Expose an API similar to System.Text.RegularExpressions so it is easy to convert existing code.
1. Demonstrate much better performance than the existing Regex, in the first instance by beating Java on [Regex-Redux](https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/regexredux.html) benchmark where currently we are 50% behind. 

Do you have any interest in collaboration on this? Work would be in the [corefxlab](https://github.com/dotnet/corefxlab/) repo. This is where we do experiments that may graduate to .NET Core itself.

[1] .NET Core 3.0 is [adding some support](https://github.com/dotnet/coreclr/issues/18013) for C++/CLI, but I expect it will only be for Windows as it depends on the MSVC compiler.

**Comment by danmosemsft** [comment]
cc @viktorhofer

**Comment by ltrzesniewski** [comment]
Hello! Sure, I'll gladly help if I can.

I originally started PCRE.NET to learn C++/CLI but I planned a rewrite to P/Invoke as the library is not usable on .NET Core. Unfortunately, this stayed on my to-do list (and the announcement that C++/CLI would be resurrected didn't help to get me started). Also, I originally made a few unfortunate design choices that hinder performance (partly due to my lack of C++/CLI knowledge at the time). 

If you want a *fast* PCRE2 library, it would require writing a small wrapper in C or C++ in order to minimize P/Invoke calls. Currently PCRE.NET issues a few P/Invoke calls per match because I chose to keep the C++/CLI part close to the PCRE2 API. That's what I planned to do with the rewrite. The C# part is mostly OK but could still be optimized for sure (less allocations for instance).

How can I help you with this?

**Comment by danmosemsft** [comment]
@ltrzesniewski I'll try to get something started over the next few days. 

Meantime in case it makes sense to reuse some of your PCRE.NET code, could you possibly clarify the LICENSE file? Just to be explicit what license your own code is under. I guess BSD which is fine, MIT is even easier.

**Comment by ltrzesniewski** [comment]
I simply used the same license as PCRE (BSD) because it seemed to be the right thing to do. I'd have preferred to use MIT for my own code but IANAL so I kept it easy (PCRE would still be BSD so the copyright notice clause would have to remain anyway).
I'll try to clarify the license file.

**Comment by ltrzesniewski** [comment]
I finally took some time to rewrite the library to target netstandard2.0 (v0.8.0), and thought you might be interested. 😉

This is a first version so I didn't take time to benchmark/optimize this, but every feature is still there with the same API surface.

**Comment by danmosemsft** [comment]
@ltrzesniewski thanks! My progress was slow (odds and ends of spare time). In very rough measurements, PCRE is 25% faster on the benchmark - but I haven't attempted to optimize it, such as reducing the interop calls as you mentioned.
https://github.com/dotnet/corefxlab/compare/master...danmosemsft:pcre?expand=1

Meanwhile someone uploaded an updated C# submission for the benchmark game that interops directly to PCRE (since they run on Linux, it's already present, thus fair game to use). It's 5x faster than Java's regexes, which is very promising.
https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/regexredux-csharpcore-8.html

**Comment by ltrzesniewski** [comment]
Nice! Of course their submission is specifically optimized for the benchmark, but that's a nice result indeed.
Now I guess I have to write a PCRE.NET version of the benchmark out of curiosity ;)

**Comment by danmosemsft** [comment]
For sure! They allow submissions  to have package references (so long as they are reasonably well recognized packages ie not just something created for the benchmark)

**Comment by ltrzesniewski** [comment]
Well, I didn't really meant to submit a benchmark that uses PCRE.NET... I think I'll implement one quickly just to get a rough comparison. Also, at this point I'm not sure that thing would qualify as C# anymore, given the package would bring lots of native code.

Anyway, I added Linux and macOS support for now, I didn't have time to optimize yet, but that should be the next step.

**Comment by danmosemsft** [comment]
I don't know their criteria exactly, but all the other submissions use a regex library (either built in or external) and I doubt they investigate what language those libraries were written in. So long as it's a widely accepted library for doing regexes, which I think yours is.

**Comment by danmosemsft** [comment]
Just updating on this, since I opened the issue we have made substantial changes to the .NET regex engine and its performance in .NET 5.0 is now very competitive. Given that, I don't plan to pursue this further. I've no doubt there's still folks that appreciate a good .NET wrapper for PCRE for either compatibility or the absolute max performance in some cases.

**Comment by ltrzesniewski** [comment]
Thanks for the update @danmosemsft! It's good to know that the .NET regex performance has been improved in 5.0. 😄 
I'll continue to update this library, as I feel the ability to use PCRE2 from .NET is something that should be possible.

I guess I can close this now, as I've actually rewritten PCRE.NET to not use C++/CLI anymore some time ago.
