### ISSUE TITLE
Arthimetic overflow exception when used in X64 Configuration

### ISSUE THREAD

**Issue by sukeshkancharla8** [ltrzesniewski/pcre-net#21]
When we use Callout functionality in PCRERegex.Match(), we are getting "An exception was thrown by the callout: Arithmetic operation resulted in an overflow." in 'X64' configuration. The same input is not giving error in case of 'Any CPU' configuration. Its been observed that the problem is during creation of PcreCallout where UIntPtr.ToUint32() is throwing this error. I have attached the place where it is throwing the exception.

![image](https://user-images.githubusercontent.com/34930258/89765184-7448a180-db13-11ea-93df-8a9191fc0fb8.png)

It would be great help to us if it gets resolved.

**Comment by ltrzesniewski** [comment]
Thanks for the bug report, I'm pretty sure I see what's going wrong here, I'll fix that.

**Comment by ltrzesniewski** [comment]
This should be fixed in v0.13.1.
