### ISSUE TITLE
Thanks for your great work !

### ISSUE THREAD

**Issue by anthony-referenceorg** [ltrzesniewski/pcre-net#23]
Like the subject says I just wanted to thank you for this fantastic solution you've made! I am parsing some very hairy Wikipedia wikitext strings in .Net, and really needed the recursive power of the Perl Regex Engine, and this project took my solution from 200+ lines of code down to just 20 lines of code using PCRE. 

This solution of yours works perfectly and I was able to use it 30 seconds after pulling it down via Nuget.

Thanks!

**Comment by ltrzesniewski** [comment]
Hey, thanks for your kind words!
I'm glad this project could help. 😄
