### ISSUE TITLE
Support for GetGroupNames()

### ISSUE THREAD

**Issue by Marusyk** [ltrzesniewski/pcre-net#27]
I wanna migrate [my library](https://github.com/Marusyk/grok.net) to this wrapper. 

There is the method [`GetGroupNames()` ](https://github.com/dotnet/runtime/blob/ac02b66e41041e1cefd355eacaddb45bcb4f1741/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs#L284) in the .NET regular expression engine that I used [here](https://github.com/Marusyk/grok.net/blob/main/src/Grok.Net/Grok.cs#L111).

Is it possible to add support for GetGroupNames to this library?

**Comment by ltrzesniewski** [comment]
They're listed in `regexInstance.PatternInfo.GroupNames`.

**Comment by Marusyk** [comment]
Cool. Thank a lot.
Here are my benchmarks before 
![image](https://github.com/ltrzesniewski/pcre-net/assets/9221694/63eb3bfb-10b6-45a3-a9f7-57d342da1e90)
and after using PCRE.NET
![image](https://github.com/ltrzesniewski/pcre-net/assets/9221694/8e1b9d0c-d5f0-4fb1-b7c9-13f0a2d9567b)
