### ISSUE TITLE
methods and properties on `matches` object

### ISSUE THREAD

**Issue by boolbag** [ltrzesniewski/pcre-net#3]
Hi Lucas,

Continuing the convo from StackOverflow. 
Excited and grateful that you've made this interface to PCRE.
Hope the info on RexEgg makes it easy for people to get started. Buried right now but hoping to flesh it out over time --- I keep coming back to the pages over time. 

At the moment I don't have issues with the package but will ask a question to get the conversation rolling.

I've always felt strange that the .NET `Match` object has a `Success` property, while the `MatchCollection` object doesn't --- you have to use `Count` or `Any()` (Linq).

How would you feel about a `Success` property for `PcreRegex.matches`?

Not a formal request, just a question to understand your design strategy.

Wishing you a terrific weekend

**Comment by ltrzesniewski** [comment]
Oh hi Rex, I didn't realize who you are, and I have to say I'm pretty surprised. :smile: 
Thanks for the ad, I certainly appreciate it a lot! 

As for your question, well... At first I wanted to closely mimic the .NET regex API, to end up with something that would be familiar to most users. So I started without giving it too much thought. That's about it - I don't like the `Success` property in the first place in the .NET API, but I took it from there anyway as a part of the whole thing. I don't like it because having a property you know will always be `true` when called from `Matches` or `Replace` is pretty much useless.

Except I'm no longer convinced trying to follow the .NET API closely is a good approach. Take a look at the regex options - most are named after PCRE, but the ones that have an equivalent in the .NET flavor are named likewise (eg `IgnoreCase` instead of `Caseless`). I hate not being consistent here so I think I'll either rename them to their PCRE name or add aliases.

API design is *hard*, so if you have any suggestions I'll gladly take some advice. At v0 I'm allowed to make breaking changes and I guess this library is mainly used by regex enthusiasts for toying around anyway so that's not a big deal.

**Comment by boolbag** [comment]
Hi Lucas,

Thank you for your thoughtful message.

Just cleaned up and beefed up the sample program, for instance to show how to use a replacement callback function. Also explained that PCRE.NET.dll will need to be distributed.

> API design is hard

It seems like a really tough job. On one side PCRE2 is a large complex beast. On the other side you have the commendable desire of providing idiomatic C#. 

I think you're doing a terrific job of managing the complexity. And fully support your thoughts about breaking changes.

Your idea about native PCRE options (or aliases) makes sense to me. As you know, PCRE has so many flags that probably won't translate to .NET. For instance recently I had to work with `PCRE2_NO_START_OPTIMIZE`. If someone is using the PCRE documentation to set flags such as this one, it makes sense to make the other flags available in the same native PCRE syntax.

Not sure that the package will be for "regex enthusiasts" for very long. :) Recently I had to translate a data extraction program from php to Python and C#. Apart from the wildly different idioms of the languages themselves, the regex definitions do not carry seamlessly from one to the other. Being able to use the same regex definitions is very attractive to me, and will be to others. Note that with the alternate *[regex package](https://pypi.python.org/pypi/regex)* Python can now behave very closely to PCRE (` \K`, `(?(DEFINE)..)`, `(*SKIP)` etc.) It's wonderful that the same is available in C#.

I wouldn't know how to advise you on the API as you have such a firmer grasp of the problem than I do. If I'm lucky to have projects for which I'm able to use PCRE.NET in the coming months, some thoughts may arise.

In the meantime, it's a treat being in touch.
A thousand thanks for the wonderful package.

Kindest regards,

R
ps: please feel free to close the ticket. More than anything, it was a chance to say hi. :)

**Comment by ltrzesniewski** [comment]
Thanks for your input, I'm glad to know the lib could be useful to you in a real project. 
I'll be happy to hear your suggestions should you have any in the future. You can still comment here if you like, even if it's closed. 

For the record, I think the next set of changes will be related to some optimization (I'll see if I can make it faster).

Best regards, 
Lucas

**Comment by boolbag** [comment]
Hi Lucas,

I LOVE that you've implemented callouts!

That's really rare. Even PHP's `preg_` functions, which have been using PCRE forever, don't support them.

I've made a [page to showcase the feature](http://www.rexegg.com/pcre-callouts.html). It's still fresh so please let me know if you have any feedback / comments, see any typos etc.

One question I have is how `PcreCalloutResult` maps to PCRE's expected return values from callouts:
> If the value is zero, matching proceeds as normal. If the value is greater than zero, matching fails at the current point, but the testing of other matching possibilities goes ahead, just as if a lookahead assertion had failed. If the value is less than zero, the match is abandoned, and the matching function returns the negative value.

I see you have three members Abort, Fail, Pass but see no mention of them in the constructor. What is the syntax to set them?

I'd like to explain that on the page.

Finally: Would you mind pinging me via a form on one of the pages on the site? That way we can get into direct email contact which can be nice for private convos.

Huge thanks for the beautiful package.

**Comment by ltrzesniewski** [comment]
Sure I've implemented them, I wanted the whole feature set :)

`PcreCalloutResult` is an *enum*, which means you should return `PcreCalloutResult.Abort`, `PcreCalloutResult.Fail` or `PcreCalloutResult.Pass`. I see you use `new PcreCalloutResult()` in your example, this is equivalent to `(PcreCalloutResult)0` which happens to be equal to `PcreCalloutResult.Pass`.

Having the possibility to return more return codes didn't make sense in C# as you can use closures to extract more information as needed. Return codes are quite useful in C but in C# we have higher-level abstractions we can make use of.

So we can simplify your example to something like this (not tested):

```C#
using System;
using PCRE;

class Program
{
  static void Main()
  {
    // === Callout Exploring Combinations ===
    var combo_regex = new PcreRegex(@"\w+(?C'temp: ')");

    combo_regex.Match("abc", callout => {
      Console.WriteLine("{0}{1}", callout.String, callout.Match.Value);
      return PcreCalloutResult.Fail;
    });

    Console.WriteLine("Press Any Key");
    Console.ReadKey();
  }
}
```

You should avoid using the `delegate` construct as it's unnecessarily bulky, prefer lambda syntax instead (this advice is valid for all C# code >= C# 3). I've also used the formatting-aware `Console.WriteLine` overload to avoid string concatenation, but this is just nitpicking for demo code.

I encourage you to take a look at the [unit tests](https://github.com/ltrzesniewski/pcre-net/tree/master/src/PCRE.NET.Tests/PcreNet) - for instance [here](https://github.com/ltrzesniewski/pcre-net/blob/066f6137704b8c9190a77c14c7113c7f347d4e97/src/PCRE.NET.Tests/PcreNet/MatchTests.cs#L179)'s the start of the callout tests. Given the lack of docs, unit tests can show you some API usage examples, which can be useful for nontrivial tasks.

If you'd like to contact me privately you can do so at *firstname dot lastname at gmail dot com* (or take a look at the e-mail address of one of my commits), but if you have more questions that could benefit other users of the lib I encourage you to post them here instead so it could be useful to others.

I'm glad you appreciate the lib :)

**Comment by boolbag** [comment]
Hi Lucas, 

Thank you so much for your thorough and helpful message!

Working too fast yesterday, I had missed that `PcreCalloutResult` was an enum. That makes a lot of sense and works perfectly.

Thank you for your lambda example, very compact. Of course in some cases you want a function that you can reuse across various matches.

I had completely missed the unit tests. You're right, that's a wonderful substitute documentation, I will dive into it. :)

> if you have more questions that could benefit other users of the lib I encourage you to post them here

Definitely, that was my intention. Thank you for being generous with your time to explain the library.

Thanks in large part to your input, I have vastly expanded my [PCRE Callout page](http://www.rexegg.com/pcre-callouts.html), which was a bit rushed yesterday, explaining the return values, showing the lambda and delegate ways of invoking the callout, expanding on the syntax (such as possible uses for arguments), and suggesting intriguing ways to use callouts to add features absent from PCRE, such as .NET's capture collections, balancing groups and infinite lookbehind**.

Warm regards,

Rex
