### ISSUE TITLE
(*NO_AUTO_POSSESS) vs PcreOptions.NoAutoPossess

### ISSUE THREAD

**Issue by boolbag** [ltrzesniewski/pcre-net#4]
Hi Lucas,

Reporting some strange behavior with the disabling of autopossessification.
No idea whether this is a problem in the API, PCRE itself, or something I've missed, and wanting to check with you before reporting it to Philip as part of an ongoing convo about callout return values.

Running the same match attempt, I get different results depending on whether the autopossess optimization is turned off via `(*NO_AUTO_POSSESS)` or `PcreOptions.NoAutoPossess`.

Do you do anything that might disable the `(*NO_AUTO_POSSESS)` pattern modifier? For instance, by inserting something in the pattern before it?
I assume not, but thought I would check with you.

Background: originally, reading the docs, I thought a callout's positive return value (`Fail` in PCRE.NET) behaved like a `(*FAIL)`. However, a short test suggested it behaved like a `(*PRUNE)`:

```
string subject = "abc";
var combo_regex = new PcreRegex(@"\w+(?C)");
combo_regex.Match(subject,
    callout =>
    {
        Console.WriteLine(callout.Match.Value);
        return PcreCalloutResult.Fail;
    }
);
```

This outputs

```
abc
bc
c
```

which is the same effect as `(*PRUNE)`.

Thinking that this result, which seemed to contradict the docs, might be the "ghost of autopossess", I tried turning it off:

```
string subject = "abc";
var combo_regex = new PcreRegex(@"(*NO_AUTO_POSSESS)\w+(?C)");
combo_regex.Match(subject,
    callout =>
    {
        Console.WriteLine(callout.Match.Value);
        return PcreCalloutResult.Fail;
    }
);
```

This yields the same `(*PRUNE)`-like output.

When I wrote to Philip to ask if he would consider adding a `(*FAIL)`-like value (which would enable an infinite lookbehind hack), he replied that a positive return value already acts like `(*FAIL)` rather than `(*PRUNE)`.

At that stage, I tried turning off autopossess using `PcreOptions.NoAutoPossess`:

```
string subject = "abc";
var combo_regex = new PcreRegex(@"\w+(?C)", PcreOptions.NoAutoPossess);
combo_regex.Match(subject,
    callout =>
    {
        Console.WriteLine(callout.Match.Value);
        return PcreCalloutResult.Fail;
    }
);
```        

Lo and behold, this behaves like a `(*FAIL)`, just as Philip had advised.

The output:
```
abc
ab
a
bc
b
c
```

So at this stage I'm trying to understand if the difference between `(*NO_AUTO_POSSESS)` and `PcreOptions.NoAutoPossess` is in the API, PCRE itself, or something else that I've missed.

**Comment by ltrzesniewski** [comment]
Nice bug you've found here, the discrepancy between `(*NO_AUTO_POSSESS)` and `PCRE2_NO_AUTO_POSSESS` is definitely an issue.

Your reasoning about auto-possessification is right, it turns your pattern into `\w++(?C)` and the `(*FAIL)` behavior skips all the backtracking steps you were expecting.

PCRE.NET always implicitly sets `PCRE2_UTF` as it works on .NET strings, which are UTF-16 encoded. Besides this, it tries to be as thin a wrapper over PCRE as possible.

I'll take a closer look at this and let you know.

**Comment by boolbag** [comment]
Thanks for your message. 
Philip says it's his bug. He committed a patch.
So as far as PCRE.NET goes, please feel free to close the issue. :)

**Comment by ltrzesniewski** [comment]
Ok! :wink: 

Well... since I actually took a look at this I may as well post my findings. I excluded PCRE.NET by testing PCRE2 itself with a C program under Cygwin.

```C
#include <stdio.h>
#include <string.h>

#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>

int callout_handler(pcre2_callout_block *c, void *data) {
	printf("Callout: [");
	fwrite(c->subject + c->start_match, 1, c->current_position - c->start_match, stdout);
	printf("]\n");
	return 1;
}

int main(int argc, char **argv) {
	pcre2_code *re;
	int error;
	PCRE2_SIZE erroffset;
	pcre2_match_context *match_context;
	pcre2_match_data *match_data;
	int rc;
	
	const PCRE2_SPTR pattern = (PCRE2_SPTR)"(*NO_AUTO_POSSESS)\\w+(?C)";
	const PCRE2_SPTR subject = (PCRE2_SPTR)"abc";
	
	char version[256];
	pcre2_config(PCRE2_CONFIG_VERSION, &version);
	
	printf("PCRE version: %s\n", version);
	printf("Pattern: %s\n", pattern);
	printf("Subject: %s\n", subject);
	
	re = pcre2_compile(pattern, PCRE2_ZERO_TERMINATED, 0, &error, &erroffset, 0);
	if (re == 0)
		return 1;
	
	match_context = pcre2_match_context_create(0);
	pcre2_set_callout(match_context, callout_handler, 0);
	
	match_data = pcre2_match_data_create_from_pattern(re, 0);
	
	rc = pcre2_match(re, subject, PCRE2_ZERO_TERMINATED, 0, 0, match_data, match_context);
	printf("Match return code: %i\n", rc);
	
	pcre2_match_context_free(match_context);
	pcre2_match_data_free(match_data);
	pcre2_code_free(re);
	return 0;
}
```

Which produces the following output:

```
$ gcc -Wall test2.c -L/usr/local/lib -lpcre2-8 && ./a.exe && echo Code: $?
PCRE version: 10.20 2015-06-30
Pattern: (*NO_AUTO_POSSESS)\w+(?C)
Subject: abc
Callout: [abc]
Callout: [bc]
Callout: [c]
Match return code: -1
Code: 0
```

This confirms the bug in PCRE2.

---

I also took a look at PCRE1, and there's no bug there.

Program:

```C
#include <stdio.h>
#include <string.h>
#include <pcre.h>

int callout_handler(pcre_callout_block *c) {
	printf("Callout: [");
	fwrite(c->subject + c->start_match, 1, c->current_position - c->start_match, stdout);
	printf("]\n");
	return 1;
}

int main(int argc, char **argv) {
	pcre *re;
	const char *error;
	int erroffset;
	int rc;
	
	const char *pattern = "(*NO_AUTO_POSSESS)\\w+(?C)";
	const char *subject = "abc";
	
	printf("PCRE version: %s\n", pcre_version());
	printf("Pattern: %s\n", pattern);
	printf("Subject: %s\n", subject);
	
	re = pcre_compile(pattern, 0, &error, &erroffset, 0);             
	if (re == 0)
		return 1;
	
	pcre_callout = callout_handler;
	
	rc = pcre_exec(re, NULL, subject, strlen(subject), 0, 0, 0, 0);
	printf("Match return code: %i\n", rc);
	
	pcre_free(re);
	return 0;
}
```

Output:

```
$ gcc -Wall test.c -lpcre && ./a.exe && echo Code: $?
PCRE version: 8.37 2015-04-28
Pattern: (*NO_AUTO_POSSESS)\w+(?C)
Subject: abc
Callout: [abc]
Callout: [ab]
Callout: [a]
Callout: [bc]
Callout: [b]
Callout: [c]
Match return code: -1
Code: 0
```

**Comment by boolbag** [comment]
Wow, thanks for that, Lucas. 
These code fragments will actually be useful to me as a stub to play with PCRE in C -- short gists are hard to find.
